spring:
  resources:
    cache:
      cachecontrol:
        max-age: 1

google:
  client:
    secret: ${GOOGLE_CLIENT_SECRET}
  credential:
    store:
      path: ${GOOGLE_CREDENTIAL_STORE_PATH}
  oauth:
    callback:
      uri: http://localhost:8080/callback