spring:
  resources:
    cache:
      cachecontrol:
        max-age: 1

# DataSource configuration
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connectionTimeout: 50000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 5

# Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.DerbyDialect