spring:

# Load config
  config:
    import: application-secrets.yml

# Cache config
  resources:
    cache:
      cachecontrol:
        max-age: 1

# DataSource configuration
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connectionTimeout: 50000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 5

# Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.DerbyDialect

# Google client configuration
google:
  oauth2:
    client:
      id: ${GOOGLE_OAUTH2_CLIENT_ID}
      secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      secret-json: ${GOOGLE_OAUTH2_CLIENT_SECRET_JSON}
      application-name: ${GOOGLE_OAUTH2_CLIENT_APPLICATION_NAME}
    callback-uri: ${GOOGLE_OAUTH2_CALLBACK_URI}
  drive:
    def-folder: ${DEF_FOLDER_NAME}